baseURL: /
languageCode: en-GB
title: Jake Turner

theme:
  - github.com/nodejh/hugo-theme-mini

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/


markup:
  highlight:
    guessSyntax: true
    style: emacs

social:
  github: github.com/jakedanielturner

params:
  author: Jake Turner
  bio: 23 | South Wales, UK | Graduate Software Engineer
  description: Personal blog for personal ramblings
  copyright: © Copyright 2023 | Jake Turner